name: ci

on:
  push:
    branches:
      - v5
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    uses: hapijs/.github/.github/workflows/ci-module.yml@workflow-min-node-version
    with:
      min-node-version: 14
